### Obtener todos los tipos de usuarios

@idOficina = 1


GET http://localhost:3000/usuariosTipo
Accept: application/json

### Obtener un tipo de usuario por ID
GET http://localhost:3000/usuariosTipo/{{idOficina}}
Accept: application/json

### Agregar un nuevo tipo de usuario
POST http://localhost:3000/usuariosTipo
Content-Type: application/json

{
    "descripcion": "Nuevo Tipo de Usuario",
    "activo": true
}

### Actualizar un tipo de usuario por ID
PUT http://localhost:3000/usuariosTipo/{{idOficina}}
Content-Type: application/json

{
    "descripcion": "Tipo de Usuario Actualizado",
    "activo": false
}

### Eliminar un tipo de usuario por ID
DELETE http://localhost:3000/usuariosTipo/{{idOficina}}